name:                arxiv-pandoc
version:             0.1.0.0
github:              "githubuser/arxiv-pandoc"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/arxiv-pandoc#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring >= 0.10 && < 0.11
- base16-bytestring == 0.1.1.7 # needed for text-conversions 0.3.0
- bytedump
- charsetdetect
- directory
- exceptions
- iconv
- magic
- text >= 1.2.3.0
- pandoc >= 2.10 && < 2.11
- path
- path-io
# - tar >= 0.5.1
- turtle
# - zio
# - zlib >= 0.6.2

library:
  source-dirs: src

executables:
  arxiv-pandoc-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - arxiv-pandoc

  arxiv-pandoc-static:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -static
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    cc-options:
    - -static
    ld-options:
    - -static
    dependencies:
    - arxiv-pandoc

tests:
  arxiv-pandoc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - arxiv-pandoc
